FROM johnnywick/ja_game:ja_python_requirement_v1 as build-env


#File: 📖 johnnywick/ja_game:ja_slot_ct_run_v1.1:  fix the __load_dataframe bug


##################
# ensure local python is preferred over distribution python
ENV PATH /usr/local/bin:$PATH

# http://bugs.python.org/issue19846
# > At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG C.UTF-8

# install ca-certificates so that HTTPS works consistently
# other runtime dependencies for Python are installed later
RUN apk add --no-cache ca-certificates

ENV GPG_KEY 0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
ENV PYTHON_VERSION 3.7.7


RUN echo "🐳:[Jean]: Using the main program: "
RUN echo "🐳:zscore_to_cdf.py"
COPY zscore_to_cdf.py .



RUN echo "install dependencies: scipy"
RUN pip3 install scipy



RUN pip3 list 
RUN echo 
RUN echo 



RUN echo "🐳:Using -h to check input_xxx statement"

ENTRYPOINT [ "python3","zscore_to_cdf.py" ]

